name: omni_jitsi_meet_web_plugin
description: Jitsi Meet Web Plugin. A plugin for integrating open source Jitsi Meet API in flutter.
version: 1.0.15
homepage: https://github.com/rijulsudhir/jitsi_meet

publish_to: none

environment:
  sdk: ">=2.18.5 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  omni_jitsi_meet_platform_interface:
    git:
      url: https://github.com/rijulsudhir/jitsi_meet.git
      ref: develop
      path: omni_jitsi_meet_platform_interface

  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.4
  meta: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: JitsiMeetPlugin
        fileName: jitsi_meet_web.dart
